#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Get the current directory
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Get the project root directory (the parent of webview)
const projectRoot = path.resolve(__dirname, '../..');

// Version source of truth = hbuilderx-plugin/package.json (HBuilderX 移植版的发布版本)。
// 这样应用内欢迎页与版本更新弹窗显示的版本与插件 package.json 一致；
// 仅当该文件缺失/无 version 时，回退到根 build.gradle（上游 IDEA 构建）。
const pluginPkgPath = path.join(projectRoot, 'hbuilderx-plugin', 'package.json');
const buildGradlePath = path.join(projectRoot, 'build.gradle');

let version = null;
let source = '';

if (fs.existsSync(pluginPkgPath)) {
  try {
    const pkg = JSON.parse(fs.readFileSync(pluginPkgPath, 'utf8'));
    if (pkg && typeof pkg.version === 'string' && pkg.version.trim()) {
      version = pkg.version.trim();
      source = 'hbuilderx-plugin/package.json';
    }
  } catch (e) {
    console.warn(`Warning: failed to parse ${pluginPkgPath}: ${e.message}`);
  }
}

if (!version && fs.existsSync(buildGradlePath)) {
  const buildGradleContent = fs.readFileSync(buildGradlePath, 'utf8');
  let versionMatch = buildGradleContent.match(/^version\s*=\s*'(.+)'$/m);
  if (!versionMatch) {
    const versionLine = buildGradleContent.split('\n').find(line => line.trim().startsWith('version ='));
    if (versionLine) versionMatch = versionLine.match(/version\s*=\s*'(.+)'/);
  }
  if (versionMatch) {
    version = versionMatch[1];
    source = 'build.gradle (fallback)';
  }
}

if (!version) {
  console.error('Error: Could not determine version from hbuilderx-plugin/package.json or build.gradle');
  process.exit(1);
}

console.log(`Found version: ${version} (source: ${source})`);

// Create the version file for the webview
const versionDir = path.join(__dirname, '../src/version');
if (!fs.existsSync(versionDir)) {
  fs.mkdirSync(versionDir, { recursive: true });
}

const versionFilePath = path.join(versionDir, 'version.ts');
const versionFileContent = `// Auto-generated version file
// This file is automatically generated during the build process
// Do not edit manually

export const APP_VERSION = '${version}';
`;

fs.writeFileSync(versionFilePath, versionFileContent);
console.log(`Version file created at: ${versionFilePath}`);
