// Auto-generated changelog file
// This file is automatically generated during the build process from CHANGELOG.md
// Do not edit manually
// Note: this file now reflects the hbuilderx-cc-gui repository (HBuilderX 移植版)

export interface ChangelogEntry {
  version: string;
  date: string;
  content: {
    en: string;
    zh: string;
  };
}

export const CHANGELOG_DATA: ChangelogEntry[] = [
  {
    version: '0.1.0',
    date: '2026-06-21',
    content: {
      en: `✨ Features
- Port the plugin to **HBuilderX**, reusing the existing webview UI and the \`ai-bridge\` backend
- Send messages with **streaming replies** end to end
- Wire up **permission / Ask / Plan** flows over file-based IPC
- Support session lifecycle: **new session, interrupt, and resume**
- Add **Provider management** (including DeepSeek) and **slash commands**
- Add **file jump-to** navigation and **IDE theme sync**
- Add **shortcut keys** and a **right-click menu** entry point
- Add a **bottom status-bar icon**
- Wire the **Skills / History / Agent / MCP** panels to their real backends`,
      zh: `✨ 新特性
- 将插件移植到 **HBuilderX**，复用现有 webview 界面与 \`ai-bridge\` 后端
- 打通**发消息 + 流式回复**全链路
- 接入**权限 / Ask / Plan** 文件 IPC 流程
- 支持会话生命周期：**新建、中断、续聊**
- 新增 **Provider 管理**（含 DeepSeek）与**斜杠命令**
- 新增**文件跳转**与 **IDE 主题同步**
- 新增**快捷键**与**右键菜单**入口
- 新增**底部状态栏图标**
- 接入 **Skills / History / Agent / MCP** 面板后端`,
    },
  },
];
